server:
  port: 8080
#  ssl:
#    key-store: .keystore
#    key-store-password: fengji
#    key-store-type: JKS
spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT
        username: test
        password: test
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    transaction:
        rollback-on-commit-failure: true

mybatis:
  mapper-locations: classpath:com/fengji/smdemo/mapper/*.xml
  type-aliases-package: com.fengji.smdemo.entity

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


thymeleaf:
   cache: false
   suffix: .html
   encoding: UTF-8
   content-type: text/html
   mode: LEGACYHTML5